INSERT INTO parkings (name, address, city, country) VALUES ('EMT', 'Cité des Microtechniques', 'Porrentruy', 'CH');
INSERT INTO parkings (name, address, city, country) VALUES ('Gare', 'Avenue de la Gare 1', 'Porrentruy', 'CH');
insert into parkings (name, address, city, country) values ('Merrick', '6076 Fuller Hill', 'Shymkent', 'KZ');
insert into parkings (name, address, city, country) values ('Anthes', '42 Bultman Alley', 'At Samat', 'TH');
insert into parkings (name, address, city, country) values ('La Follette', '1 Briar Crest Alley', 'Chenhu', 'CN');
insert into parkings (name, address, city, country) values ('Oak Valley', '53661 Marcy Avenue', 'Arnhem', 'NL');
insert into parkings (name, address, city, country) values ('Maryland', '589 Glacier Hill Lane', 'Kerbuyan', 'ID');
insert into parkings (name, address, city, country) values ('Fallview', '97 Sycamore Court', 'Gijon', 'ES');
insert into parkings (name, address, city, country) values ('Jana', '64941 Atwood Circle', 'Decatur', 'US');
insert into parkings (name, address, city, country) values ('Main', '16067 Kinsman Drive', 'Itami', 'JP');
insert into parkings (name, address, city, country) values ('Crescent Oaks', '8118 Buell Crossing', 'Fortios', 'PT');
insert into parkings (name, address, city, country) values ('High Crossing', '8 Thierer Place', 'Nihaona', 'ID');
insert into parkings (name, address, city, country) values ('Shelley', '52841 Old Gate Terrace', 'Banikoara', 'BJ');
insert into parkings (name, address, city, country) values ('Garrison', '05 Chive Alley', 'Velikovechnoye', 'RU');
insert into parkings (name, address, city, country) values ('Lukken', '092 Green Ridge Park', 'Xiaozhi', 'CN');
insert into parkings (name, address, city, country) values ('Lillian', '70 Comanche Park', 'Belfast', 'ZA');
insert into parkings (name, address, city, country) values ('Ramsey', '7 Mendota Park', 'La Unión', 'CO');
insert into parkings (name, address, city, country) values ('Surrey', '9223 Logan Junction', 'Klagenfurt am Wörthersee', 'AT');
insert into parkings (name, address, city, country) values ('Harbort', '3216 Anthes Court', 'Chanhe', 'CN');
insert into parkings (name, address, city, country) values ('Valley Edge', '5524 Rigney Alley', 'San Diego', 'MX');
insert into parkings (name, address, city, country) values ('Lillian', '7700 High Crossing Lane', 'Londrina', 'BR');
insert into parkings (name, address, city, country) values ('Pierstorff', '60 American Ash Circle', 'Kubangkondang', 'ID');
insert into parkings (name, address, city, country) values ('Forest Run', '392 Nelson Trail', 'Lescar', 'FR');
insert into parkings (name, address, city, country) values ('Atwood', '60 Susan Avenue', 'Katrineholm', 'SE');
insert into parkings (name, address, city, country) values ('Graedel', '486 Everett Alley', 'Konëvo', 'RU');
insert into parkings (name, address, city, country) values ('Johnson', '5 Main Crossing', 'Ransiki', 'ID');
insert into parkings (name, address, city, country) values ('Northland', '4295 Northwestern Crossing', 'Carmen de Viboral', 'CO');
insert into parkings (name, address, city, country) values ('Golf Course', '3176 Moulton Crossing', 'Acandí', 'CO');
insert into parkings (name, address, city, country) values ('Texas', '85 7th Road', 'Jiyizhuang', 'CN');
insert into parkings (name, address, city, country) values ('Graedel', '0279 Pawling Avenue', 'San Martin', 'MX');
insert into parkings (name, address, city, country) values ('Prairieview', '3432 Golf View Junction', 'Valle de La Pascua', 'VE');
insert into parkings (name, address, city, country) values ('Sullivan', '7 5th Court', 'Naj‘ Ḩammādī', 'EG');
insert into parkings (name, address, city, country) values ('Nevada', '360 Monica Avenue', 'Aktsyabrski', 'BY');
insert into parkings (name, address, city, country) values ('Kenwood', '6163 Arapahoe Plaza', 'Kaiyuan', 'CN');
insert into parkings (name, address, city, country) values ('Carberry', '428 2nd Street', 'Sundbyberg', 'SE');
insert into parkings (name, address, city, country) values ('Fallview', '43204 Nancy Pass', 'Atlasovo', 'RU');
insert into parkings (name, address, city, country) values ('8th', '60 North Park', 'Teresina', 'BR');
insert into parkings (name, address, city, country) values ('Thierer', '655 Debra Road', 'Zmiennica', 'PL');
insert into parkings (name, address, city, country) values ('Carpenter', '4862 Glacier Hill Center', 'Fengcheng', 'CN');
insert into parkings (name, address, city, country) values ('Arizona', '4705 Manitowish Junction', 'Bau', 'ID');
insert into parkings (name, address, city, country) values ('Anderson', '47 Steensland Circle', 'Sindang', 'ID');
insert into parkings (name, address, city, country) values ('Porter', '793 Veith Drive', 'Longbo', 'CN');
insert into parkings (name, address, city, country) values ('Boyd', '8 Dayton Alley', 'Colomi', 'BO');
insert into parkings (name, address, city, country) values ('Mallory', '874 Nancy Terrace', 'Dolní Bojanovice', 'CZ');
insert into parkings (name, address, city, country) values ('Hoard', '3445 Sachs Terrace', 'Brunflo', 'SE');
insert into parkings (name, address, city, country) values ('Farragut', '58165 Maple Hill', 'Quế Sơn', 'VN');
insert into parkings (name, address, city, country) values ('Hazelcrest', '377 Del Mar Avenue', 'Labé', 'GN');
insert into parkings (name, address, city, country) values ('Schlimgen', '3 Melrose Drive', 'Henan’an', 'CN');
insert into parkings (name, address, city, country) values ('Service', '74 Johnson Hill', 'Nadvoitsy', 'RU');
insert into parkings (name, address, city, country) values ('Linden', '47518 Glacier Hill Trail', 'Hällefors', 'SE');
insert into parkings (name, address, city, country) values ('Knutson', '862 Novick Drive', 'Yaojiagou', 'CN');
insert into parkings (name, address, city, country) values ('Westridge', '57 4th Junction', 'Parzęczew', 'PL');
insert into parkings (name, address, city, country) values ('Clove', '86 Schmedeman Point', 'Albacete', 'ES');
insert into parkings (name, address, city, country) values ('Petterle', '6 Summit Plaza', 'Wolofeo', 'ID');
insert into parkings (name, address, city, country) values ('Briar Crest', '2061 Esker Road', 'Wiang Nuea', 'TH');
insert into parkings (name, address, city, country) values ('Ridge Oak', '1654 Everett Plaza', 'Jinhe', 'CN');
insert into parkings (name, address, city, country) values ('Gulseth', '285 Vidon Court', 'Guadalupe', 'MX');
insert into parkings (name, address, city, country) values ('Oak', '56864 American Park', 'Igurusi', 'TZ');
insert into parkings (name, address, city, country) values ('Cascade', '249 Westend Lane', 'Sabirabad', 'AZ');
insert into parkings (name, address, city, country) values ('Hauk', '048 Daystar Avenue', 'Sāqayn', 'YE');
insert into parkings (name, address, city, country) values ('Ryan', '1690 Pierstorff Place', 'Charlton', 'GB');
insert into parkings (name, address, city, country) values ('Saint Paul', '71 Carioca Pass', 'Uglegorsk', 'RU');
insert into parkings (name, address, city, country) values ('Scofield', '90400 Jenna Plaza', 'Meijiang', 'CN');
insert into parkings (name, address, city, country) values ('Killdeer', '1818 North Trail', 'Guxi', 'CN');
insert into parkings (name, address, city, country) values ('Sutherland', '4 Crest Line Park', 'Mercedes', 'AR');
insert into parkings (name, address, city, country) values ('Stuart', '4710 Aberg Place', 'Lomba do Loução', 'PT');
insert into parkings (name, address, city, country) values ('Carey', '1 Anniversary Point', 'Sukawening', 'ID');
insert into parkings (name, address, city, country) values ('Trailsway', '1379 Bobwhite Alley', 'Sablé-sur-Sarthe', 'FR');
insert into parkings (name, address, city, country) values ('Scott', '9 Cascade Circle', 'Pokrovskoye', 'RU');
insert into parkings (name, address, city, country) values ('Oak Valley', '735 Holy Cross Trail', 'Estrela', 'BR');
insert into parkings (name, address, city, country) values ('Bartillon', '469 Morningstar Drive', 'Béthune', 'FR');
insert into parkings (name, address, city, country) values ('Almo', '4125 Heffernan Circle', 'Poteran', 'ID');
insert into parkings (name, address, city, country) values ('Onsgard', '72521 Everett Circle', 'Birmingham', 'GB');
insert into parkings (name, address, city, country) values ('Farmco', '863 Brown Drive', 'Gibsons', 'CA');
insert into parkings (name, address, city, country) values ('Prairie Rose', '57 Thompson Lane', 'Yandun', 'CN');
insert into parkings (name, address, city, country) values ('Fordem', '92 Monument Road', 'Pejë', 'XK');
insert into parkings (name, address, city, country) values ('Ruskin', '7 Warbler Center', 'Waerana', 'ID');
insert into parkings (name, address, city, country) values ('Warrior', '446 Stoughton Court', 'Tranås', 'SE');
insert into parkings (name, address, city, country) values ('Meadow Ridge', '1 Northridge Way', 'Likasi', 'CD');
insert into parkings (name, address, city, country) values ('Melvin', '12418 Northland Trail', 'Ailuk', 'MH');
insert into parkings (name, address, city, country) values ('Starling', '872 Magdeline Place', 'Tarata', 'PE');
insert into parkings (name, address, city, country) values ('Old Shore', '3 Tony Circle', 'Halimpu', 'ID');
insert into parkings (name, address, city, country) values ('Northland', '288 Lillian Hill', 'Beichengqu', 'CN');
insert into parkings (name, address, city, country) values ('American', '641 Sunfield Circle', 'Jianqiao', 'CN');
insert into parkings (name, address, city, country) values ('Spohn', '78005 Petterle Drive', 'Dubrava', 'HR');
insert into parkings (name, address, city, country) values ('Beilfuss', '58229 Starling Terrace', 'Valença', 'BR');
insert into parkings (name, address, city, country) values ('Gateway', '34 Monument Point', 'Znamenskoye', 'RU');
insert into parkings (name, address, city, country) values ('Corry', '5 Buell Point', 'Banatski Dvor', 'RS');
insert into parkings (name, address, city, country) values ('Hermina', '81 Claremont Place', 'Hispania', 'CO');
insert into parkings (name, address, city, country) values ('Melvin', '906 Trailsway Park', 'Mons', 'BE');
insert into parkings (name, address, city, country) values ('Heffernan', '381 Morning Circle', 'Kamionka', 'PL');
insert into parkings (name, address, city, country) values ('Pawling', '9 Melody Lane', 'Ilha Solteira', 'BR');
insert into parkings (name, address, city, country) values ('5th', '07 Utah Court', 'Quintas', 'PT');
insert into parkings (name, address, city, country) values ('Delaware', '52 Jenifer Terrace', 'Chacarita', 'CR');
insert into parkings (name, address, city, country) values ('Columbus', '45588 Northport Drive', 'Fuhe', 'CN');
insert into parkings (name, address, city, country) values ('Prentice', '13229 Westend Hill', 'Monte Redondo', 'PT');
insert into parkings (name, address, city, country) values ('Anderson', '508 Atwood Crossing', 'Varge Mondar', 'PT');
insert into parkings (name, address, city, country) values ('Heath', '2 Monica Street', 'Laranjal Paulista', 'BR');
insert into parkings (name, address, city, country) values ('Troy', '787 Saint Paul Drive', 'Arvika', 'SE');
insert into parkings (name, address, city, country) values ('Summit', '76 6th Place', 'Pembroke', 'CA');

INSERT INTO sensors (sigfox_id, fk_parking) VALUES ('tu24h9h', 1);
INSERT INTO sensors (sigfox_id, fk_parking) VALUES ('rf58fh', 1);
INSERT INTO sensors (sigfox_id, fk_parking) VALUES ('tr34zh', 2);
insert into sensors (sigfox_id, fk_parking) values ('8wbx03', 75);
insert into sensors (sigfox_id, fk_parking) values ('6ht5xa', 7);
insert into sensors (sigfox_id, fk_parking) values ('3r7pky', 44);
insert into sensors (sigfox_id, fk_parking) values ('530hiz', 23);
insert into sensors (sigfox_id, fk_parking) values ('xyli5f', 82);
insert into sensors (sigfox_id, fk_parking) values ('dhcer8', 69);
insert into sensors (sigfox_id, fk_parking) values ('w2lf12', 60);
insert into sensors (sigfox_id, fk_parking) values ('0c1sme', 24);
insert into sensors (sigfox_id, fk_parking) values ('eqvmpt', 81);
insert into sensors (sigfox_id, fk_parking) values ('juqmt7', 43);
insert into sensors (sigfox_id, fk_parking) values ('zwe3b5', 22);
insert into sensors (sigfox_id, fk_parking) values ('k1wfdn', 71);
insert into sensors (sigfox_id, fk_parking) values ('1tgr8x', 30);
insert into sensors (sigfox_id, fk_parking) values ('mds3vx', 79);
insert into sensors (sigfox_id, fk_parking) values ('zrx1yp', 60);
insert into sensors (sigfox_id, fk_parking) values ('lcdgzf', 46);
insert into sensors (sigfox_id, fk_parking) values ('4baj69', 62);
insert into sensors (sigfox_id, fk_parking) values ('b2a6ai', 36);
insert into sensors (sigfox_id, fk_parking) values ('efyn3s', 19);
insert into sensors (sigfox_id, fk_parking) values ('43kfav', 26);
insert into sensors (sigfox_id, fk_parking) values ('9dw0si', 5);
insert into sensors (sigfox_id, fk_parking) values ('2ssx5m', 22);
insert into sensors (sigfox_id, fk_parking) values ('ioshq5', 38);
insert into sensors (sigfox_id, fk_parking) values ('ic75ma', 45);
insert into sensors (sigfox_id, fk_parking) values ('v7fyhy', 35);
insert into sensors (sigfox_id, fk_parking) values ('lfypor', 6);
insert into sensors (sigfox_id, fk_parking) values ('cla5x1', 20);
insert into sensors (sigfox_id, fk_parking) values ('ieutbu', 87);
insert into sensors (sigfox_id, fk_parking) values ('zn53d0', 41);
insert into sensors (sigfox_id, fk_parking) values ('qdcyvt', 51);
insert into sensors (sigfox_id, fk_parking) values ('46l8c6', 63);
insert into sensors (sigfox_id, fk_parking) values ('zsissk', 5);
insert into sensors (sigfox_id, fk_parking) values ('tg3p3q', 68);
insert into sensors (sigfox_id, fk_parking) values ('2rtdhm', 58);
insert into sensors (sigfox_id, fk_parking) values ('cx58co', 11);
insert into sensors (sigfox_id, fk_parking) values ('dgd6b6', 17);
insert into sensors (sigfox_id, fk_parking) values ('h65u08', 2);
insert into sensors (sigfox_id, fk_parking) values ('l9shwz', 93);
insert into sensors (sigfox_id, fk_parking) values ('oeedsv', 10);
insert into sensors (sigfox_id, fk_parking) values ('t51rep', 17);
insert into sensors (sigfox_id, fk_parking) values ('pufj3c', 49);
insert into sensors (sigfox_id, fk_parking) values ('aqnml7', 96);
insert into sensors (sigfox_id, fk_parking) values ('4xkm10', 33);
insert into sensors (sigfox_id, fk_parking) values ('84q1wr', 47);
insert into sensors (sigfox_id, fk_parking) values ('29edcl', 42);
insert into sensors (sigfox_id, fk_parking) values ('ur1z6g', 93);
insert into sensors (sigfox_id, fk_parking) values ('zlawpi', 14);
insert into sensors (sigfox_id, fk_parking) values ('wex0xg', 7);
insert into sensors (sigfox_id, fk_parking) values ('l2n7da', 14);
insert into sensors (sigfox_id, fk_parking) values ('h6snlq', 42);
insert into sensors (sigfox_id, fk_parking) values ('e4sfyf', 39);
insert into sensors (sigfox_id, fk_parking) values ('4d78ai', 77);
insert into sensors (sigfox_id, fk_parking) values ('4q5mod', 12);
insert into sensors (sigfox_id, fk_parking) values ('4op6tb', 23);
insert into sensors (sigfox_id, fk_parking) values ('s39fd4', 90);
insert into sensors (sigfox_id, fk_parking) values ('e3k9cm', 38);
insert into sensors (sigfox_id, fk_parking) values ('mo373f', 74);
insert into sensors (sigfox_id, fk_parking) values ('ek4whc', 42);
insert into sensors (sigfox_id, fk_parking) values ('67x4tb', 60);
insert into sensors (sigfox_id, fk_parking) values ('hwdhk5', 67);
insert into sensors (sigfox_id, fk_parking) values ('hxj341', 29);
insert into sensors (sigfox_id, fk_parking) values ('uf21pw', 22);
insert into sensors (sigfox_id, fk_parking) values ('be296m', 66);
insert into sensors (sigfox_id, fk_parking) values ('jxhl8t', 84);
insert into sensors (sigfox_id, fk_parking) values ('miu5ai', 17);
insert into sensors (sigfox_id, fk_parking) values ('6qctx4', 76);
insert into sensors (sigfox_id, fk_parking) values ('s4dgad', 76);
insert into sensors (sigfox_id, fk_parking) values ('74kgqb', 37);
insert into sensors (sigfox_id, fk_parking) values ('fd02wa', 93);
insert into sensors (sigfox_id, fk_parking) values ('6sf978', 1);
insert into sensors (sigfox_id, fk_parking) values ('dhg7wh', 55);
insert into sensors (sigfox_id, fk_parking) values ('b2z9rd', 98);
insert into sensors (sigfox_id, fk_parking) values ('62r0z4', 93);
insert into sensors (sigfox_id, fk_parking) values ('g0nm4h', 5);
insert into sensors (sigfox_id, fk_parking) values ('iguwyp', 3);
insert into sensors (sigfox_id, fk_parking) values ('dbmyp2', 76);
insert into sensors (sigfox_id, fk_parking) values ('7co76p', 75);
insert into sensors (sigfox_id, fk_parking) values ('zp425m', 85);
insert into sensors (sigfox_id, fk_parking) values ('wyg3or', 20);
insert into sensors (sigfox_id, fk_parking) values ('n20dul', 83);
insert into sensors (sigfox_id, fk_parking) values ('vnojsb', 88);
insert into sensors (sigfox_id, fk_parking) values ('0f7dbp', 12);
insert into sensors (sigfox_id, fk_parking) values ('yt8hsi', 73);
insert into sensors (sigfox_id, fk_parking) values ('26ozu4', 68);
insert into sensors (sigfox_id, fk_parking) values ('32ytdj', 17);
insert into sensors (sigfox_id, fk_parking) values ('o2a19d', 51);
insert into sensors (sigfox_id, fk_parking) values ('0g1puk', 77);
insert into sensors (sigfox_id, fk_parking) values ('a6q4ot', 65);
insert into sensors (sigfox_id, fk_parking) values ('0r2kzj', 78);
insert into sensors (sigfox_id, fk_parking) values ('md6o75', 91);
insert into sensors (sigfox_id, fk_parking) values ('8rbmu2', 66);
insert into sensors (sigfox_id, fk_parking) values ('zgtpcj', 59);
insert into sensors (sigfox_id, fk_parking) values ('29urji', 19);
insert into sensors (sigfox_id, fk_parking) values ('xz52q8', 74);
insert into sensors (sigfox_id, fk_parking) values ('zmmz1m', 92);
insert into sensors (sigfox_id, fk_parking) values ('en02y1', 33);
insert into sensors (sigfox_id, fk_parking) values ('cnrfxh', 67);

INSERT INTO results (occupation, date, sequence, fk_sensor) VALUES (1, '2021-01-28 02:03:52', 15, 1);
INSERT INTO results (occupation, date, sequence, fk_sensor) VALUES (0, '2021-02-28 05:03:52', 15, 2);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-11 15:23:53', 357, 17);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-08-13 19:46:43', 19, 82);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-01-23 12:53:45', 279, 45);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-02-27 00:48:15', 288, 30);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-11-05 17:33:56', 218, 93);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-10-14 21:56:43', 340, 47);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-27 02:03:55', 249, 37);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-02-23 18:24:39', 113, 56);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-10-31 15:18:22', 297, 99);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-02-22 16:36:51', 24, 25);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-11-12 06:50:45', 379, 87);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-09-17 11:22:25', 267, 48);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-09-12 22:44:26', 297, 39);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-11-05 01:45:51', 414, 44);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-15 07:09:18', 413, 31);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-06-01 10:33:44', 243, 41);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-06-03 16:40:15', 176, 87);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-17 19:33:11', 427, 39);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-11-12 23:14:06', 249, 93);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-08-26 01:38:06', 27, 70);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-07-01 14:22:17', 274, 96);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-08-18 16:32:48', 473, 29);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-01-16 19:28:44', 299, 1);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-02-15 17:59:27', 415, 70);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-01-31 14:06:48', 109, 90);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-02-19 14:42:02', 87, 4);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-05-20 18:55:37', 150, 57);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-03-29 00:33:18', 48, 13);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-01-22 16:03:12', 294, 96);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-03-14 09:24:38', 164, 43);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-08-07 12:03:01', 179, 15);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-01 09:58:59', 5, 21);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-02-12 08:05:44', 195, 96);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-18 01:41:24', 282, 8);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-12-11 07:13:21', 369, 17);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-03-19 17:19:24', 461, 55);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-01-10 21:00:50', 309, 80);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-03-05 21:08:39', 90, 43);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-09-01 23:36:29', 440, 58);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-09-09 04:07:40', 236, 16);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-10-10 21:33:53', 212, 51);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-04-27 20:46:22', 383, 78);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-02-02 16:45:45', 286, 74);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-11-04 10:07:30', 18, 81);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-04-11 07:13:54', 384, 47);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-11-26 17:05:32', 378, 48);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-05-01 04:49:44', 241, 63);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-09-13 18:45:55', 484, 65);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-04-27 06:24:50', 500, 87);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-08-05 22:49:09', 171, 60);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-02 21:05:31', 327, 68);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-06-01 15:57:06', 171, 3);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-03-28 19:54:17', 249, 85);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-10-30 02:53:34', 377, 31);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-04-30 17:03:12', 263, 8);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-03-24 22:10:07', 249, 96);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-21 04:06:37', 320, 50);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-09-25 23:26:24', 292, 25);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-08-27 10:38:46', 419, 59);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-02-24 03:09:07', 96, 25);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-09-28 02:33:48', 209, 56);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-07-13 05:00:00', 256, 77);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-01-03 01:59:59', 259, 95);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-03-28 10:14:25', 8, 84);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-01-20 00:55:47', 346, 89);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-04-10 17:16:33', 95, 84);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-12-01 15:10:11', 471, 47);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-05-25 11:12:54', 110, 78);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-04-19 22:29:51', 215, 8);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-03-01 04:42:36', 450, 26);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-11-17 00:58:51', 413, 93);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-26 12:58:14', 451, 74);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-01-15 10:04:34', 308, 96);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-06-24 15:32:58', 198, 26);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-09-01 03:27:33', 44, 81);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-03-13 10:08:16', 375, 8);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-01-31 09:08:27', 26, 42);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-15 03:52:21', 470, 10);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-12 11:35:13', 362, 52);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-15 04:07:00', 261, 46);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-15 01:40:26', 372, 24);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-05-22 07:03:29', 250, 63);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-12 23:41:09', 29, 70);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-11-04 03:34:12', 258, 7);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-03-31 22:51:03', 99, 99);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-08-16 02:05:29', 428, 33);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-06-29 02:21:21', 53, 61);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-01-09 19:03:56', 260, 57);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2020-12-24 22:26:29', 465, 43);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-10-31 21:39:24', 274, 21);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-01-01 14:40:30', 239, 9);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-01-25 13:50:46', 460, 73);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-08-19 08:45:31', 399, 33);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-08-08 06:08:15', 281, 16);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2020-12-25 20:44:09', 430, 30);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-06-02 16:59:21', 221, 94);
insert into results (occupation, date, sequence, fk_sensor) values (1, '2021-07-10 18:02:30', 9, 85);
insert into results (occupation, date, sequence, fk_sensor) values (0, '2021-07-18 00:16:17', 421, 52);